default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: postgres
  password: today@123

development:
  <<: *default
  database: dev_xyz

test:
  <<: *default
  database: test_xyz

production:
  <<: *default
  database: prod_xyz
